"""
Curated all-time leaders, championship greats, Mount Rushmore defaults.
Fallback when live APIs fail.
"""
from __future__ import annotations
from typing import Dict, List

ALL_TIME_LEADERS: Dict[str, Dict[str, List[dict]]] = {
    "browns": {
        "Passing Yards": [
            {"rank": 1, "player": "Brian Sipe", "value": "23,713", "note": "Franchise legend"},
            {"rank": 2, "player": "Bernie Kosar", "value": "15,328", "note": ""},
            {"rank": 3, "player": "Baker Mayfield", "value": "14,120", "note": ""},
            {"rank": 4, "player": "Otto Graham", "value": "23,584*", "note": "AAFC+NFL"},
            {"rank": 5, "player": "Tim Couch", "value": "11,198", "note": ""},
            {"rank": 6, "player": "Derek Anderson", "value": "7,307", "note": ""},
            {"rank": 7, "player": "Colt McCoy", "value": "6,332", "note": ""},
            {"rank": 8, "player": "Brandon Weeden", "value": "5,671", "note": ""},
            {"rank": 9, "player": "Kelly Holcomb", "value": "4,829", "note": ""},
            {"rank": 10, "player": "Jake Delhomme", "value": "2,921", "note": ""},
        ],
        "Rushing Yards": [
            {"rank": 1, "player": "Jim Brown", "value": "12,312", "note": "NFL icon"},
            {"rank": 2, "player": "Leroy Kelly", "value": "7,274", "note": ""},
            {"rank": 3, "player": "Mike Pruitt", "value": "6,540", "note": ""},
            {"rank": 4, "player": "Jamall Lewis", "value": "6,264", "note": ""},
            {"rank": 5, "player": "Nick Chubb", "value": "6,500+", "note": "Active era"},
            {"rank": 6, "player": "Kevin Mack", "value": "5,123", "note": ""},
            {"rank": 7, "player": "Earnest Byner", "value": "4,377", "note": ""},
            {"rank": 8, "player": "Peyton Hillis", "value": "2,368", "note": ""},
            {"rank": 9, "player": "Jerome Harrison", "value": "1,646", "note": ""},
            {"rank": 10, "player": "William Green", "value": "1,593", "note": ""},
        ],
        "Receiving Yards": [
            {"rank": 1, "player": "Ozzie Newsome", "value": "7,980", "note": ""},
            {"rank": 2, "player": "Reggie Rucker", "value": "4,953", "note": ""},
            {"rank": 3, "player": "Derrick Alexander", "value": "4,898", "note": ""},
            {"rank": 4, "player": "Webster Slaughter", "value": "4,834", "note": ""},
            {"rank": 5, "player": "Kellen Winslow Jr.", "value": "3,775", "note": ""},
            {"rank": 6, "player": "Paul Warfield", "value": "3,086", "note": ""},
            {"rank": 7, "player": "Josh Gordon", "value": "3,015", "note": ""},
            {"rank": 8, "player": "Jarvis Landry", "value": "3,000+", "note": ""},
            {"rank": 9, "player": "Amari Cooper", "value": "2,500+", "note": ""},
            {"rank": 10, "player": "Greg Little", "value": "2,000+", "note": ""},
        ],
        "Sacks": [
            {"rank": 1, "player": "Myles Garrett", "value": "100+", "note": "Active superstar"},
            {"rank": 2, "player": "Clay Matthews", "value": "62.0", "note": ""},
            {"rank": 3, "player": "Michael Dean Perry", "value": "51.0", "note": ""},
            {"rank": 4, "player": "Reggie Camp", "value": "47.0", "note": ""},
            {"rank": 5, "player": "Rob Burnett", "value": "40.5", "note": ""},
            {"rank": 6, "player": "Anthony Pleasant", "value": "38.0", "note": ""},
            {"rank": 7, "player": "Kamerion Wimbley", "value": "26.5", "note": ""},
            {"rank": 8, "player": "Jabaal Sheard", "value": "20.5", "note": ""},
            {"rank": 9, "player": "Courtney Brown", "value": "19.0", "note": ""},
            {"rank": 10, "player": "Emmanuel Ogbah", "value": "15.0+", "note": ""},
        ],
    },
    "guardians": {
        "Hits": [
            {"rank": 1, "player": "Nap Lajoie", "value": "2,046", "note": ""},
            {"rank": 2, "player": "Tris Speaker", "value": "1,965", "note": ""},
            {"rank": 3, "player": "Earl Averill", "value": "1,903", "note": ""},
            {"rank": 4, "player": "Omar Vizquel", "value": "1,616", "note": ""},
            {"rank": 5, "player": "Joe Sewell", "value": "1,592", "note": ""},
            {"rank": 6, "player": "Kenny Lofton", "value": "1,512", "note": ""},
            {"rank": 7, "player": "Lou Boudreau", "value": "1,417", "note": ""},
            {"rank": 8, "player": "Jim Thome", "value": "1,399", "note": ""},
            {"rank": 9, "player": "Al Rosen", "value": "1,239", "note": ""},
            {"rank": 10, "player": "Minnie Minoso", "value": "1,115", "note": ""},
        ],
        "Home Runs": [
            {"rank": 1, "player": "Jim Thome", "value": "337", "note": ""},
            {"rank": 2, "player": "Albert Belle", "value": "242", "note": ""},
            {"rank": 3, "player": "Manny Ramirez", "value": "236", "note": ""},
            {"rank": 4, "player": "Earl Averill", "value": "226", "note": ""},
            {"rank": 5, "player": "Larry Doby", "value": "215", "note": ""},
            {"rank": 6, "player": "Andre Thornton", "value": "214", "note": ""},
            {"rank": 7, "player": "Travis Hafner", "value": "200", "note": ""},
            {"rank": 8, "player": "Al Rosen", "value": "192", "note": ""},
            {"rank": 9, "player": "Carlos Santana", "value": "200+", "note": ""},
            {"rank": 10, "player": "Jose Ramirez", "value": "200+", "note": "Active"},
        ],
        "Wins (Pitching)": [
            {"rank": 1, "player": "Bob Feller", "value": "266", "note": ""},
            {"rank": 2, "player": "Mel Harder", "value": "223", "note": ""},
            {"rank": 3, "player": "Bob Lemon", "value": "207", "note": ""},
            {"rank": 4, "player": "Stan Coveleski", "value": "172", "note": ""},
            {"rank": 5, "player": "Early Wynn", "value": "164", "note": ""},
            {"rank": 6, "player": "Addie Joss", "value": "160", "note": ""},
            {"rank": 7, "player": "Sam McDowell", "value": "122", "note": ""},
            {"rank": 8, "player": "CC Sabathia", "value": "99", "note": ""},
            {"rank": 9, "player": "Corey Kluber", "value": "98", "note": ""},
            {"rank": 10, "player": "Shane Bieber", "value": "70+", "note": ""},
        ],
        "Strikeouts": [
            {"rank": 1, "player": "Bob Feller", "value": "2,581", "note": ""},
            {"rank": 2, "player": "Sam McDowell", "value": "2,159", "note": ""},
            {"rank": 3, "player": "Bob Lemon", "value": "1,277", "note": ""},
            {"rank": 4, "player": "Early Wynn", "value": "1,277", "note": ""},
            {"rank": 5, "player": "CC Sabathia", "value": "1,265", "note": ""},
            {"rank": 6, "player": "Corey Kluber", "value": "1,261", "note": ""},
            {"rank": 7, "player": "Luis Tiant", "value": "1,172", "note": ""},
            {"rank": 8, "player": "Mel Harder", "value": "1,161", "note": ""},
            {"rank": 9, "player": "Shane Bieber", "value": "1,000+", "note": ""},
            {"rank": 10, "player": "Bartolo Colon", "value": "829", "note": ""},
        ],
    },
    "cavaliers": {
        "Points": [
            {"rank": 1, "player": "LeBron James", "value": "23,119+", "note": ""},
            {"rank": 2, "player": "Zydrunas Ilgauskas", "value": "10,616", "note": ""},
            {"rank": 3, "player": "Brad Daugherty", "value": "10,389", "note": ""},
            {"rank": 4, "player": "Austin Carr", "value": "10,265", "note": ""},
            {"rank": 5, "player": "Bingo Smith", "value": "10,029", "note": ""},
            {"rank": 6, "player": "Mark Price", "value": "9,543", "note": ""},
            {"rank": 7, "player": "Hot Rod Williams", "value": "8,504", "note": ""},
            {"rank": 8, "player": "Kyrie Irving", "value": "8,232", "note": ""},
            {"rank": 9, "player": "World B. Free", "value": "6,536", "note": ""},
            {"rank": 10, "player": "Kevin Love", "value": "6,000+", "note": ""},
        ],
        "Rebounds": [
            {"rank": 1, "player": "Zydrunas Ilgauskas", "value": "5,904", "note": ""},
            {"rank": 2, "player": "LeBron James", "value": "5,500+", "note": ""},
            {"rank": 3, "player": "Brad Daugherty", "value": "5,117", "note": ""},
            {"rank": 4, "player": "Hot Rod Williams", "value": "4,591", "note": ""},
            {"rank": 5, "player": "Jim Chones", "value": "4,202", "note": ""},
            {"rank": 6, "player": "Kevin Love", "value": "4,000+", "note": ""},
            {"rank": 7, "player": "Tristan Thompson", "value": "4,000+", "note": ""},
            {"rank": 8, "player": "Anderson Varejao", "value": "3,700+", "note": ""},
            {"rank": 9, "player": "Campy Russell", "value": "3,000+", "note": ""},
            {"rank": 10, "player": "Larry Nance Jr.", "value": "2,000+", "note": ""},
        ],
        "Assists": [
            {"rank": 1, "player": "LeBron James", "value": "6,228+", "note": ""},
            {"rank": 2, "player": "Mark Price", "value": "4,206", "note": ""},
            {"rank": 3, "player": "John Bagley", "value": "2,943", "note": ""},
            {"rank": 4, "player": "Kyrie Irving", "value": "2,500+", "note": ""},
            {"rank": 5, "player": "Foots Walker", "value": "2,500+", "note": ""},
            {"rank": 6, "player": "Terrell Brandon", "value": "2,500+", "note": ""},
            {"rank": 7, "player": "Darius Garland", "value": "2,000+", "note": "Active"},
            {"rank": 8, "player": "Andre Miller", "value": "2,000+", "note": ""},
            {"rank": 9, "player": "Craig Ehlo", "value": "2,000+", "note": ""},
            {"rank": 10, "player": "Ramon Sessions", "value": "1,500+", "note": ""},
        ],
        "Steals": [
            {"rank": 1, "player": "LeBron James", "value": "1,300+", "note": ""},
            {"rank": 2, "player": "Mark Price", "value": "734", "note": ""},
            {"rank": 3, "player": "Craig Ehlo", "value": "700+", "note": ""},
            {"rank": 4, "player": "Hot Rod Williams", "value": "600+", "note": ""},
            {"rank": 5, "player": "Kyrie Irving", "value": "500+", "note": ""},
            {"rank": 6, "player": "Brevin Knight", "value": "500+", "note": ""},
            {"rank": 7, "player": "Darius Garland", "value": "400+", "note": ""},
            {"rank": 8, "player": "Anderson Varejao", "value": "400+", "note": ""},
            {"rank": 9, "player": "Larry Nance", "value": "400+", "note": ""},
            {"rank": 10, "player": "Bobby Phills", "value": "350+", "note": ""},
        ],
    },
    "osu_football": {
        "Passing Yards": [
            {"rank": 1, "player": "J.T. Barrett", "value": "9,434", "note": ""},
            {"rank": 2, "player": "C.J. Stroud", "value": "8,000+", "note": ""},
            {"rank": 3, "player": "Art Schlichter", "value": "7,547", "note": ""},
            {"rank": 4, "player": "Bobby Hoying", "value": "7,232", "note": ""},
            {"rank": 5, "player": "Joe Germaine", "value": "6,370", "note": ""},
            {"rank": 6, "player": "Terrelle Pryor", "value": "6,177", "note": ""},
            {"rank": 7, "player": "Troy Smith", "value": "5,720", "note": "Heisman"},
            {"rank": 8, "player": "Justin Fields", "value": "3,273", "note": ""},
            {"rank": 9, "player": "Braxton Miller", "value": "3,000+", "note": ""},
            {"rank": 10, "player": "Cardale Jones", "value": "1,500+", "note": ""},
        ],
        "Rushing Yards": [
            {"rank": 1, "player": "Archie Griffin", "value": "5,589", "note": "2x Heisman"},
            {"rank": 2, "player": "Ezekiel Elliott", "value": "3,961", "note": ""},
            {"rank": 3, "player": "Eddie George", "value": "3,600", "note": "Heisman"},
            {"rank": 4, "player": "Beanie Wells", "value": "3,382", "note": ""},
            {"rank": 5, "player": "J.K. Dobbins", "value": "3,000+", "note": ""},
            {"rank": 6, "player": "Carlos Hyde", "value": "3,000+", "note": ""},
            {"rank": 7, "player": "Robert Smith", "value": "3,000+", "note": ""},
            {"rank": 8, "player": "Keith Byars", "value": "3,000+", "note": ""},
            {"rank": 9, "player": "TreVeyon Henderson", "value": "2,500+", "note": ""},
            {"rank": 10, "player": "Braxton Miller", "value": "2,500+", "note": ""},
        ],
        "Receiving Yards": [
            {"rank": 1, "player": "David Boston", "value": "2,855", "note": ""},
            {"rank": 2, "player": "Chris Olave", "value": "2,500+", "note": ""},
            {"rank": 3, "player": "Michael Jenkins", "value": "2,500+", "note": ""},
            {"rank": 4, "player": "Santonio Holmes", "value": "2,200+", "note": ""},
            {"rank": 5, "player": "Garrett Wilson", "value": "2,000+", "note": ""},
            {"rank": 6, "player": "Ted Ginn Jr.", "value": "2,000+", "note": ""},
            {"rank": 7, "player": "Devin Smith", "value": "2,000+", "note": ""},
            {"rank": 8, "player": "Jaxon Smith-Njigba", "value": "1,600+", "note": ""},
            {"rank": 9, "player": "Emeka Egbuka", "value": "1,500+", "note": ""},
            {"rank": 10, "player": "Parris Campbell", "value": "1,500+", "note": ""},
        ],
        "Tackles": [
            {"rank": 1, "player": "Chris Spielman", "value": "546", "note": ""},
            {"rank": 2, "player": "Marcus Marek", "value": "500+", "note": ""},
            {"rank": 3, "player": "Tom Cousineau", "value": "500+", "note": ""},
            {"rank": 4, "player": "James Laurinaitis", "value": "375+", "note": ""},
            {"rank": 5, "player": "A.J. Hawk", "value": "350+", "note": ""},
            {"rank": 6, "player": "Ryan Shazier", "value": "300+", "note": ""},
            {"rank": 7, "player": "Malik Harrison", "value": "250+", "note": ""},
            {"rank": 8, "player": "Pete Werner", "value": "200+", "note": ""},
            {"rank": 9, "player": "Tuf Borland", "value": "200+", "note": ""},
            {"rank": 10, "player": "Cody Simon", "value": "150+", "note": ""},
        ],
    },
    "osu_mbb": {
        "Points": [
            {"rank": 1, "player": "Dennis Hopson", "value": "2,096", "note": ""},
            {"rank": 2, "player": "Jerry Lucas", "value": "1,990", "note": ""},
            {"rank": 3, "player": "Michael Redd", "value": "1,879", "note": ""},
            {"rank": 4, "player": "Jimmy Jackson", "value": "1,785", "note": ""},
            {"rank": 5, "player": "Evan Turner", "value": "1,700+", "note": ""},
            {"rank": 6, "player": "Jared Sullinger", "value": "1,500+", "note": ""},
            {"rank": 7, "player": "Keita Bates-Diop", "value": "1,400+", "note": ""},
            {"rank": 8, "player": "Aaron Craft", "value": "1,200+", "note": ""},
            {"rank": 9, "player": "E.J. Liddell", "value": "1,200+", "note": ""},
            {"rank": 10, "player": "D'Angelo Russell", "value": "1,000+", "note": ""},
        ],
        "Rebounds": [
            {"rank": 1, "player": "Jerry Lucas", "value": "1,411", "note": ""},
            {"rank": 2, "player": "Herb Williams", "value": "1,000+", "note": ""},
            {"rank": 3, "player": "Clark Kellogg", "value": "900+", "note": ""},
            {"rank": 4, "player": "Jared Sullinger", "value": "900+", "note": ""},
            {"rank": 5, "player": "Keita Bates-Diop", "value": "700+", "note": ""},
            {"rank": 6, "player": "Kaleb Wesson", "value": "600+", "note": ""},
            {"rank": 7, "player": "Evan Turner", "value": "600+", "note": ""},
            {"rank": 8, "player": "David Lighty", "value": "500+", "note": ""},
            {"rank": 9, "player": "Kyle Young", "value": "500+", "note": ""},
            {"rank": 10, "player": "Zed Key", "value": "400+", "note": ""},
        ],
        "Assists": [
            {"rank": 1, "player": "Aaron Craft", "value": "700+", "note": ""},
            {"rank": 2, "player": "Troy Taylor", "value": "500+", "note": ""},
            {"rank": 3, "player": "Scoonie Penn", "value": "450+", "note": ""},
            {"rank": 4, "player": "Evan Turner", "value": "350+", "note": ""},
            {"rank": 5, "player": "William Buford", "value": "300+", "note": ""},
            {"rank": 6, "player": "CJ Jackson", "value": "250+", "note": ""},
            {"rank": 7, "player": "Bruce Thornton", "value": "200+", "note": ""},
            {"rank": 8, "player": "D'Angelo Russell", "value": "200+", "note": ""},
            {"rank": 9, "player": "Meechie Johnson", "value": "200+", "note": ""},
            {"rank": 10, "player": "Jamari Wheeler", "value": "150+", "note": ""},
        ],
        "Steals": [
            {"rank": 1, "player": "Aaron Craft", "value": "300+", "note": ""},
            {"rank": 2, "player": "Troy Taylor", "value": "200+", "note": ""},
            {"rank": 3, "player": "David Lighty", "value": "150+", "note": ""},
            {"rank": 4, "player": "Evan Turner", "value": "150+", "note": ""},
            {"rank": 5, "player": "Scoonie Penn", "value": "140+", "note": ""},
            {"rank": 6, "player": "William Buford", "value": "120+", "note": ""},
            {"rank": 7, "player": "D'Angelo Russell", "value": "80+", "note": ""},
            {"rank": 8, "player": "Keita Bates-Diop", "value": "80+", "note": ""},
            {"rank": 9, "player": "CJ Jackson", "value": "70+", "note": ""},
            {"rank": 10, "player": "Malaki Branham", "value": "50+", "note": ""},
        ],
    },
    "crew": {
        "Goals": [
            {"rank": 1, "player": "Gyasi Zardes", "value": "70+", "note": "Club legend"},
            {"rank": 2, "player": "Justin Meram", "value": "50+", "note": ""},
            {"rank": 3, "player": "Federico Higuain", "value": "50+", "note": ""},
            {"rank": 4, "player": "Cucho Hernandez", "value": "40+", "note": "Modern star"},
            {"rank": 5, "player": "Diego Rossi", "value": "20+", "note": ""},
            {"rank": 6, "player": "Lucas Zelarayan", "value": "30+", "note": ""},
            {"rank": 7, "player": "Pedro Santos", "value": "25+", "note": ""},
            {"rank": 8, "player": "Wil Trapp", "value": "—", "note": "Midfield engine"},
            {"rank": 9, "player": "Darlington Nagbe", "value": "—", "note": "Homegrown icon"},
            {"rank": 10, "player": "Patrick Mullins", "value": "15+", "note": ""},
        ],
        "Appearances": [
            {"rank": 1, "player": "Wil Trapp", "value": "250+", "note": ""},
            {"rank": 2, "player": "Justin Meram", "value": "200+", "note": ""},
            {"rank": 3, "player": "Josh Williams", "value": "200+", "note": ""},
            {"rank": 4, "player": "Darlington Nagbe", "value": "180+", "note": ""},
            {"rank": 5, "player": "Federico Higuain", "value": "150+", "note": ""},
            {"rank": 6, "player": "Gyasi Zardes", "value": "150+", "note": ""},
            {"rank": 7, "player": "Zach Steffen", "value": "100+", "note": ""},
            {"rank": 8, "player": "Pedro Santos", "value": "120+", "note": ""},
            {"rank": 9, "player": "Lucas Zelarayan", "value": "100+", "note": ""},
            {"rank": 10, "player": "Jonathan Mensah", "value": "100+", "note": ""},
        ],
    },
    "bluejackets": {
        "Goals": [
            {"rank": 1, "player": "Rick Nash", "value": "289", "note": ""},
            {"rank": 2, "player": "Cam Atkinson", "value": "200+", "note": ""},
            {"rank": 3, "player": "Nick Foligno", "value": "150+", "note": ""},
            {"rank": 4, "player": "Boone Jenner", "value": "150+", "note": ""},
            {"rank": 5, "player": "Zach Werenski", "value": "100+", "note": ""},
            {"rank": 6, "player": "Artemi Panarin", "value": "80+", "note": "CBJ years"},
            {"rank": 7, "player": "Seth Jones", "value": "50+", "note": ""},
            {"rank": 8, "player": "Oliver Bjorkstrand", "value": "100+", "note": ""},
            {"rank": 9, "player": "Johnny Gaudreau", "value": "—", "note": ""},
            {"rank": 10, "player": "Patrik Laine", "value": "—", "note": ""},
        ],
        "Points": [
            {"rank": 1, "player": "Rick Nash", "value": "547", "note": ""},
            {"rank": 2, "player": "Cam Atkinson", "value": "400+", "note": ""},
            {"rank": 3, "player": "Nick Foligno", "value": "350+", "note": ""},
            {"rank": 4, "player": "Boone Jenner", "value": "300+", "note": ""},
            {"rank": 5, "player": "Zach Werenski", "value": "300+", "note": ""},
            {"rank": 6, "player": "Artemi Panarin", "value": "200+", "note": ""},
            {"rank": 7, "player": "Seth Jones", "value": "200+", "note": ""},
            {"rank": 8, "player": "Oliver Bjorkstrand", "value": "250+", "note": ""},
            {"rank": 9, "player": "Ryan Johansen", "value": "200+", "note": ""},
            {"rank": 10, "player": "Jakub Voracek", "value": "150+", "note": ""},
        ],
    },
    "usmnt": {
        "Caps": [
            {"rank": 1, "player": "Cobi Jones", "value": "164", "note": ""},
            {"rank": 2, "player": "Landon Donovan", "value": "157", "note": ""},
            {"rank": 3, "player": "Michael Bradley", "value": "151", "note": ""},
            {"rank": 4, "player": "Clint Dempsey", "value": "141", "note": ""},
            {"rank": 5, "player": "Jeff Agoos", "value": "134", "note": ""},
            {"rank": 6, "player": "Marcelo Balboa", "value": "127", "note": ""},
            {"rank": 7, "player": "DaMarcus Beasley", "value": "126", "note": ""},
            {"rank": 8, "player": "Tim Howard", "value": "121", "note": ""},
            {"rank": 9, "player": "Jozy Altidore", "value": "115", "note": ""},
            {"rank": 10, "player": "Christian Pulisic", "value": "70+", "note": "Active"},
        ],
        "Goals": [
            {"rank": 1, "player": "Clint Dempsey", "value": "57", "note": ""},
            {"rank": 2, "player": "Landon Donovan", "value": "57", "note": ""},
            {"rank": 3, "player": "Jozy Altidore", "value": "42", "note": ""},
            {"rank": 4, "player": "Eric Wynalda", "value": "34", "note": ""},
            {"rank": 5, "player": "Brian McBride", "value": "30", "note": ""},
            {"rank": 6, "player": "Joe-Max Moore", "value": "24", "note": ""},
            {"rank": 7, "player": "Christian Pulisic", "value": "25+", "note": ""},
            {"rank": 8, "player": "Earnie Stewart", "value": "17", "note": ""},
            {"rank": 9, "player": "Bruce Murray", "value": "21", "note": ""},
            {"rank": 10, "player": "Herculez Gomez", "value": "—", "note": ""},
        ],
    },
    "usab": {
        "Olympic Golds (era)": [
            {"rank": 1, "player": "Michael Jordan", "value": "2", "note": "1984, 1992"},
            {"rank": 2, "player": "LeBron James", "value": "3", "note": "2008, 2012, 2024"},
            {"rank": 3, "player": "Kevin Durant", "value": "4", "note": "Most golds"},
            {"rank": 4, "player": "Carmelo Anthony", "value": "3", "note": ""},
            {"rank": 5, "player": "David Robinson", "value": "2", "note": ""},
            {"rank": 6, "player": "Kobe Bryant", "value": "2", "note": ""},
            {"rank": 7, "player": "Chris Paul", "value": "1+", "note": ""},
            {"rank": 8, "player": "Stephen Curry", "value": "1+", "note": "2024"},
            {"rank": 9, "player": "Anthony Davis", "value": "1+", "note": ""},
            {"rank": 10, "player": "Jayson Tatum", "value": "1+", "note": ""},
        ],
        "Points (Olympics)": [
            {"rank": 1, "player": "Carmelo Anthony", "value": "336", "note": ""},
            {"rank": 2, "player": "Kevin Durant", "value": "300+", "note": ""},
            {"rank": 3, "player": "LeBron James", "value": "250+", "note": ""},
            {"rank": 4, "player": "David Robinson", "value": "200+", "note": ""},
            {"rank": 5, "player": "Michael Jordan", "value": "—", "note": ""},
            {"rank": 6, "player": "Kobe Bryant", "value": "—", "note": ""},
            {"rank": 7, "player": "Paul George", "value": "—", "note": ""},
            {"rank": 8, "player": "Kevin Love", "value": "—", "note": ""},
            {"rank": 9, "player": "Anthony Edwards", "value": "—", "note": ""},
            {"rank": 10, "player": "Devin Booker", "value": "—", "note": ""},
        ],
    },
    "kent_mbb": {
        "Points": [
            {"rank": 1, "player": "Antonio Gates", "value": "—", "note": "Before NFL"},
            {"rank": 2, "player": "Earl Jordan", "value": "—", "note": ""},
            {"rank": 3, "player": "Justin Greene", "value": "—", "note": ""},
            {"rank": 4, "player": "Chris Evans", "value": "—", "note": ""},
            {"rank": 5, "player": "Anthony Vander Horst", "value": "—", "note": ""},
            {"rank": 6, "player": "Jimmy Hall", "value": "—", "note": ""},
            {"rank": 7, "player": "Jaylin Walker", "value": "—", "note": ""},
            {"rank": 8, "player": "Miryne Thomas", "value": "—", "note": ""},
            {"rank": 9, "player": "Sincere Carry", "value": "—", "note": ""},
            {"rank": 10, "player": "Giovanni Santiago", "value": "—", "note": ""},
        ],
        "Rebounds": [
            {"rank": 1, "player": "Justin Greene", "value": "—", "note": ""},
            {"rank": 2, "player": "Jimmy Hall", "value": "—", "note": ""},
            {"rank": 3, "player": "Miryne Thomas", "value": "—", "note": ""},
            {"rank": 4, "player": "Chris Evans", "value": "—", "note": ""},
            {"rank": 5, "player": "Anthony Vander Horst", "value": "—", "note": ""},
            {"rank": 6, "player": "Jaylin Walker", "value": "—", "note": ""},
            {"rank": 7, "player": "Cli'Ron Hornbeak", "value": "—", "note": ""},
            {"rank": 8, "player": "Julius Rollins", "value": "—", "note": ""},
            {"rank": 9, "player": "Reggie Bass", "value": "—", "note": ""},
            {"rank": 10, "player": "Jalen Sullinger", "value": "—", "note": ""},
        ],
    },
    "rhs_football": {
        "Program Notes": [
            {"rank": 1, "player": "Program", "value": "OHSAA", "note": "Reynoldsburg Raiders"},
            {"rank": 2, "player": "Conference", "value": "OCC", "note": "Ohio Capital Conference"},
            {"rank": 3, "player": "Colors", "value": "Purple/Orange", "note": ""},
            {"rank": 4, "player": "City", "value": "Reynoldsburg, OH", "note": ""},
            {"rank": 5, "player": "Level", "value": "High School", "note": "Live scores via local/MaxPreps style feeds when available"},
            {"rank": 6, "player": "—", "value": "—", "note": "Stats update seasonally"},
            {"rank": 7, "player": "—", "value": "—", "note": ""},
            {"rank": 8, "player": "—", "value": "—", "note": ""},
            {"rank": 9, "player": "—", "value": "—", "note": ""},
            {"rank": 10, "player": "—", "value": "—", "note": ""},
        ],
    },
    "rhs_mbb": {
        "Program Notes": [
            {"rank": 1, "player": "Program", "value": "OHSAA", "note": "Reynoldsburg Raiders Boys BB"},
            {"rank": 2, "player": "Conference", "value": "OCC", "note": ""},
            {"rank": 3, "player": "Colors", "value": "Purple/Orange", "note": ""},
            {"rank": 4, "player": "City", "value": "Reynoldsburg, OH", "note": ""},
            {"rank": 5, "player": "Level", "value": "High School", "note": ""},
            {"rank": 6, "player": "—", "value": "—", "note": ""},
            {"rank": 7, "player": "—", "value": "—", "note": ""},
            {"rank": 8, "player": "—", "value": "—", "note": ""},
            {"rank": 9, "player": "—", "value": "—", "note": ""},
            {"rank": 10, "player": "—", "value": "—", "note": ""},
        ],
    },
    "tiffin_tf": {
        "Program Notes": [
            {"rank": 1, "player": "Program", "value": "NCAA DII", "note": "Tiffin Dragons"},
            {"rank": 2, "player": "Conference", "value": "G-MAC", "note": ""},
            {"rank": 3, "player": "Colors", "value": "Purple/Gold", "note": ""},
            {"rank": 4, "player": "City", "value": "Tiffin, OH", "note": ""},
            {"rank": 5, "player": "Sport", "value": "Men's Track & Field", "note": ""},
            {"rank": 6, "player": "—", "value": "—", "note": "Meet results via TFRRS / school site"},
            {"rank": 7, "player": "—", "value": "—", "note": ""},
            {"rank": 8, "player": "—", "value": "—", "note": ""},
            {"rank": 9, "player": "—", "value": "—", "note": ""},
            {"rank": 10, "player": "—", "value": "—", "note": ""},
        ],
    },

}

CHAMPIONSHIP_GREATS: Dict[str, List[dict]] = {
    "browns": [
        {"player": "Otto Graham", "era": "1946-1955", "titles": "7 AAFC/NFL titles", "why": "Ultimate winner at QB"},
        {"player": "Jim Brown", "era": "1957-1965", "titles": "1964 NFL Champ", "why": "Greatest RB"},
        {"player": "Lou Groza", "era": "1946-1967", "titles": "Multiple", "why": "The Toe"},
        {"player": "Marion Motley", "era": "1946-1953", "titles": "Multiple", "why": "Integration pioneer"},
        {"player": "Ozzie Newsome", "era": "1978-1990", "titles": "HOF TE", "why": "Wizard of Oz"},
        {"player": "Joe Thomas", "era": "2007-2017", "titles": "10x Pro Bowl", "why": "Iron man LT"},
        {"player": "Myles Garrett", "era": "2017-", "titles": "DPOY caliber", "why": "Generational edge"},
        {"player": "Bernie Kosar", "era": "1985-1993", "titles": "Deep runs", "why": "Hometown hero"},
    ],
    "guardians": [
        {"player": "Bob Feller", "era": "1936-1956", "titles": "1948 WS", "why": "Rapid Robert"},
        {"player": "Larry Doby", "era": "1947-1959", "titles": "1948 WS", "why": "AL integration pioneer"},
        {"player": "Satchel Paige", "era": "1948-1949", "titles": "1948 WS", "why": "Legend"},
        {"player": "Lou Boudreau", "era": "1938-1950", "titles": "1948 WS PM", "why": "Player-manager"},
        {"player": "Bob Lemon", "era": "1941-1958", "titles": "1948 WS", "why": "Ace"},
        {"player": "Tris Speaker", "era": "1916-1926", "titles": "1920 WS", "why": "Grey Eagle"},
        {"player": "Nap Lajoie", "era": "1902-1914", "titles": "Early dynasty", "why": "Franchise icon"},
        {"player": "Jim Thome", "era": "1991-2002", "titles": "Power icon", "why": "Gentleman slugger"},
    ],
    "cavaliers": [
        {"player": "LeBron James", "era": "2003-2018", "titles": "2016 NBA Champ", "why": "Ended the drought"},
        {"player": "Kyrie Irving", "era": "2011-2017", "titles": "2016 NBA Champ", "why": "Game 7 dagger"},
        {"player": "Kevin Love", "era": "2014-2023", "titles": "2016 NBA Champ", "why": "Stretch big"},
        {"player": "Mark Price", "era": "1986-1995", "titles": "Deep runs", "why": "Elite PG"},
        {"player": "Brad Daugherty", "era": "1986-1994", "titles": "90s core", "why": "Franchise C"},
        {"player": "Zydrunas Ilgauskas", "era": "1997-2010", "titles": "Fan favorite", "why": "Big Z"},
        {"player": "Austin Carr", "era": "1971-1980", "titles": "Original star", "why": "Mr. Cavalier"},
        {"player": "Bingo Smith", "era": "1970-1979", "titles": "Early years", "why": "Scoring wing"},
    ],
    "osu_football": [
        {"player": "Archie Griffin", "era": "1972-1975", "titles": "National runs", "why": "Only 2x Heisman"},
        {"player": "Troy Smith", "era": "2003-2006", "titles": "2006 run", "why": "Heisman QB"},
        {"player": "Eddie George", "era": "1992-1995", "titles": "Elite seasons", "why": "Heisman RB"},
        {"player": "Orlando Pace", "era": "1994-1996", "titles": "Dominant OL", "why": "Road grader"},
        {"player": "Chris Spielman", "era": "1984-1987", "titles": "Defensive heart", "why": "LB legend"},
        {"player": "Jack Tatum", "era": "1968-1970", "titles": "Super teams", "why": "The Assassin"},
        {"player": "Chase Young", "era": "2017-2019", "titles": "Elite defense", "why": "Edge force"},
        {"player": "Nick Bosa", "era": "2016-2018", "titles": "Elite defense", "why": "Edge force"},
    ],
    "osu_mbb": [
        {"player": "Jerry Lucas", "era": "1959-1962", "titles": "National POY", "why": "All-time great"},
        {"player": "John Havlicek", "era": "1959-1962", "titles": "Championship DNA", "why": "Before Celtics"},
        {"player": "Jimmy Jackson", "era": "1989-1992", "titles": "Contender", "why": "Complete wing"},
        {"player": "Evan Turner", "era": "2007-2010", "titles": "National POY", "why": "Do-it-all"},
        {"player": "Michael Redd", "era": "1997-2000", "titles": "Scoring", "why": "Pure shooter"},
        {"player": "Aaron Craft", "era": "2010-2014", "titles": "Defense", "why": "B1G pest"},
        {"player": "Jared Sullinger", "era": "2010-2012", "titles": "Final Four", "why": "Double-doubles"},
        {"player": "Dennis Hopson", "era": "1983-1987", "titles": "Scoring champ", "why": "Buckets"},
    ],
}

DEFAULT_RUSHMORE: Dict[str, List[str]] = {
    "crew": ["Gyasi Zardes", "Darlington Nagbe", "Federico Higuain", "Cucho Hernandez"],
    "bluejackets": ["Rick Nash", "Cam Atkinson", "Boone Jenner", "Zach Werenski"],
    "usmnt": ["Landon Donovan", "Clint Dempsey", "Christian Pulisic", "Tim Howard"],
    "usab": ["Michael Jordan", "LeBron James", "Kevin Durant", "Kobe Bryant"],
    "kent_mbb": ["Antonio Gates", "Justin Greene", "Jimmy Hall", "Sincere Carry"],
    "rhs_football": ["Program Legend 1", "Program Legend 2", "Program Legend 3", "Program Legend 4"],
    "rhs_mbb": ["Program Legend 1", "Program Legend 2", "Program Legend 3", "Program Legend 4"],
    "tiffin_tf": ["Program Legend 1", "Program Legend 2", "Program Legend 3", "Program Legend 4"],

    "browns": ["Jim Brown", "Otto Graham", "Ozzie Newsome", "Myles Garrett"],
    "guardians": ["Bob Feller", "Larry Doby", "Tris Speaker", "Jim Thome"],
    "cavaliers": ["LeBron James", "Kyrie Irving", "Mark Price", "Brad Daugherty"],
    "osu_football": ["Archie Griffin", "Troy Smith", "Orlando Pace", "Chris Spielman"],
    "osu_mbb": ["Jerry Lucas", "John Havlicek", "Jimmy Jackson", "Evan Turner"],
}

PLAYER_POOL: Dict[str, List[str]] = {}
for k, cats in ALL_TIME_LEADERS.items():
    names = []
    for entries in cats.values():
        for e in entries:
            names.append(e["player"])
    for g in CHAMPIONSHIP_GREATS.get(k, []):
        names.append(g["player"])
    seen = set()
    uniq = []
    for n in names:
        if n not in seen:
            seen.add(n)
            uniq.append(n)
    PLAYER_POOL[k] = uniq
