"""
PDF export for team snapshot (scores, standings snippet, journal).
Uses fpdf2 when available; Pillow multi-page fallback otherwise.
"""
from __future__ import annotations
import io
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional


def export_team_pdf(
    team_name: str,
    record: str,
    games: List[dict],
    standings_rows: List[dict],
    news: List[dict],
    journal: Optional[List[dict]] = None,
) -> bytes:
    try:
        return _fpdf_export(team_name, record, games, standings_rows, news, journal)
    except Exception:
        return _pillow_pdf(team_name, record, games, standings_rows, news)


def _fpdf_export(team_name, record, games, standings_rows, news, journal) -> bytes:
    from fpdf import FPDF

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=14)
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(0, 10, "SO!SB!Y! Team Report", ln=True)
    pdf.set_font("Helvetica", "", 12)
    pdf.cell(0, 8, f"{team_name}  |  Record: {record}", ln=True)
    pdf.cell(0, 8, datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"), ln=True)
    pdf.ln(4)

    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 8, "Scores / games", ln=True)
    pdf.set_font("Helvetica", "", 10)
    if not games:
        pdf.cell(0, 6, "No games in window.", ln=True)
    for g in (games or [])[:12]:
        line = (
            f"{g.get('away_team','')} {g.get('away_score','–')} @ "
            f"{g.get('home_team','')} {g.get('home_score','–')}  "
            f"[{g.get('status') or g.get('detail') or ''}]"
        )
        pdf.multi_cell(0, 5, line[:120])

    pdf.ln(3)
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 8, "Standings (snippet)", ln=True)
    pdf.set_font("Helvetica", "", 10)
    for r in (standings_rows or [])[:15]:
        pdf.cell(0, 5, f"{r.get('Team','—')}  W:{r.get('W','—')} L:{r.get('L','—')} PCT:{r.get('PCT','—')}", ln=True)

    pdf.ln(3)
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 8, "News", ln=True)
    pdf.set_font("Helvetica", "", 10)
    for a in (news or [])[:10]:
        pdf.multi_cell(0, 5, f"- {a.get('headline','')[:110]}")

    if journal:
        pdf.add_page()
        pdf.set_font("Helvetica", "B", 14)
        pdf.cell(0, 8, "Hypothetical bet journal", ln=True)
        pdf.set_font("Helvetica", "", 10)
        for j in journal[:30]:
            pdf.multi_cell(
                0, 5,
                f"{j.get('side','')}  odds={j.get('odds')}  stake={j.get('stake')}  "
                f"{j.get('result')}  pnl={j.get('pnl')}  {j.get('note','')}"[:120]
            )

    pdf.set_font("Helvetica", "I", 8)
    pdf.cell(0, 8, "Generated by SO!SB!Y! — educational use only", ln=True)
    out = pdf.output()
    if isinstance(out, bytearray):
        return bytes(out)
    if isinstance(out, bytes):
        return out
    # older API wrote to path only — use dest=S
    return bytes(pdf.output(dest="S"))


def _pillow_pdf(team_name, record, games, standings_rows, news) -> bytes:
    from PIL import Image, ImageDraw, ImageFont

    pages = []
    W, H = 612, 792  # letter-ish points at 72dpi

    def new_page():
        img = Image.new("RGB", (W, H), (255, 255, 255))
        d = ImageDraw.Draw(img)
        try:
            font = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", 12)
            bold = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", 16)
        except Exception:
            font = bold = ImageFont.load_default()
        return img, d, font, bold

    img, d, font, bold = new_page()
    y = 40
    d.text((40, y), "SO!SB!Y! Team Report", fill=(20, 20, 20), font=bold)
    y += 28
    d.text((40, y), f"{team_name} | {record}", fill=(40, 40, 40), font=font)
    y += 22
    d.text((40, y), "Scores:", fill=(0, 0, 0), font=bold)
    y += 20
    for g in (games or [])[:15]:
        line = f"{g.get('away_team','')} {g.get('away_score','–')} @ {g.get('home_team','')} {g.get('home_score','–')}"
        d.text((40, y), line[:90], fill=(30, 30, 30), font=font)
        y += 16
        if y > H - 60:
            pages.append(img)
            img, d, font, bold = new_page()
            y = 40
    pages.append(img)

    buf = io.BytesIO()
    if len(pages) == 1:
        pages[0].save(buf, format="PDF", resolution=100.0)
    else:
        pages[0].save(buf, format="PDF", save_all=True, append_images=pages[1:], resolution=100.0)
    return buf.getvalue()
